/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Item } from "./components/strant-list-item/item";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface StrantListItem {
        "item": Item;
    }
    interface StrantSortedList {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStrantListItemElement extends Components.StrantListItem, HTMLStencilElement {
    }
    var HTMLStrantListItemElement: {
        prototype: HTMLStrantListItemElement;
        new (): HTMLStrantListItemElement;
    };
    interface HTMLStrantSortedListElement extends Components.StrantSortedList, HTMLStencilElement {
    }
    var HTMLStrantSortedListElement: {
        prototype: HTMLStrantSortedListElement;
        new (): HTMLStrantSortedListElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "strant-list-item": HTMLStrantListItemElement;
        "strant-sorted-list": HTMLStrantSortedListElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface StrantListItem {
        "item"?: Item;
    }
    interface StrantSortedList {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "strant-list-item": StrantListItem;
        "strant-sorted-list": StrantSortedList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "strant-list-item": LocalJSX.StrantListItem & JSXBase.HTMLAttributes<HTMLStrantListItemElement>;
            "strant-sorted-list": LocalJSX.StrantSortedList & JSXBase.HTMLAttributes<HTMLStrantSortedListElement>;
        }
    }
}
